---
- hosts: web_nodes
  become: yes
  tags: [web]
  vars:
    my_domain: 3.122.228.239
    my_private: 172.31.20.204
    my_private2: 172.31.22.203
  roles:
    - nginx

  tasks:
    - include_tasks: tasks/os-dependencies.yml

- hosts: stats_nodes
  become: yes
  tags: [stats_server]
  vars:
    metrics_db_name: "metrics"
    metrics_db_pass: "metrics"
    metrics_db_user: "metrics"
    datasource_name: "my-influx"
    grafana_http_port: 3000
    telegraf_configuration: "telegraf_default.conf"
  roles:
    - influxdb
    - grafana
    - telegraf
  tasks:
    - include_tasks: tasks/configure-grafana.yml

- hosts: app_nodes
  become: yes
  vars:
    jar_location: carrental/car_rental.jar
    app_location: /opt/carrental/car_rental.jar
    app_user: carrental
  roles:
     - application
     - telegraf