---
- hosts: web_nodes
  become: yes
  tags: [web]
  vars:
    my_domain: 3.121.29.42
    proxy_to: ec2-3-121-29-42.eu-central-1.compute.amazonaws.com
  roles:
    - nginx
    - telegraf
  tasks:
    - include_tasks: tasks/os-dependencies.yml